$script = <<-SCRIPT
apt-get update && apt upgrade -y 
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "promserver" do |promserver|
    promserver.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
#    promserver.vm.synced_folder "./prometheus-files", "/home/vagrant/prometheus-files"
    promserver.vm.network "public_network", ip: "192.168.88.150", bridge: "enp4s0"
    promserver.vm.provision "shell", inline: $script
  end
end
